### ISSUE TITLE
dyngen: unexpected external symbol __stack_chk_fail

### ISSUE THREAD

**Issue by probonopd** [cebix/macemu#103]
Build fails with `dyngen: unexpected external symbol __stack_chk_fail`.

```
# Build host: ubuntu-16.04-desktop-amd64.iso

sudo apt-get install automake libx11-dev libpthread-stubs0-dev build-essential autoconf libgtk2.0-de

cd macemu-master/SheepShaver/src/Unix/

./autogen.sh
make

# ./dyngen -o basic-dyngen-ops.hpp obj/basic-dyngen-ops.o
# dyngen: unexpected external symbol __stack_chk_fail
# Makefile:225: recipe for target 'basic-dyngen-ops.hpp' failed
# make: *** [basic-dyngen-ops.hpp] Error 1
```

Can someone please post step-by-step instructions on how to compile this on recent Ubuntu versions?

**Comment by asvitkine** [comment]
Sounds like basic-dyngen-ops.o is being compiled with stack checking
enabled, which confuses the dyngen tool. You can probably add
--fno-stack-protector to the basic-dyngen-ops.o build command line to
prevent this.

See http://wiki.osdev.org/Stack_Smashing_Protector for more info.

**Comment by asvitkine** [comment]
Just to follow up on this, looks like someone else solved this on the
forums via:

CXXFLAGS="-fno-stack-protector -g -O2" CFLAGS="-fno-stack-protector -O2"
./autogen.sh

However, it's unfortunate that this extra step is required. Ideally, the
autogen script could detect and add the appropriate flags itself during
configure time. Patches welcome!

**Comment by probonopd** [comment]
Thanks @asvitkine, works for me.
