### ISSUE TITLE
a new macports basiliskii buildfile to try

### ISSUE THREAD

**Issue by kencu** [cebix/macemu#109]
Hi, everyone. I've been building basiliskii with macports for a year or so now, and before that manually. I just updated the build file today to the current 20170509 sources and it seems to build and run very nicely on my MacPro / Sierra machine.

I haven't uploaded it to the main macports repository just yet, but if anyone here wants to try / test / comment you can do quite easily by getting the build file and patches here:

<https://github.com/kencu/myports/tree/master/emulators/basiliskii>

Works well I think. Thanks to everyone for all the work on basiliskii over the years. I really enjoy using it.

**Comment by kencu** [comment]
By default, the macports build file as written enables 32bit, the JIT, and SLIRP networking. It uses the SDL interface, although you can manually change it to the old MacOSX interface (it still builds!) if you're on 10.4 or 10.5 and see how that looked.

I would like to enhance the Portfile to make the GDK GUI using whatever architecture the person wants (usually x86_64) rather than force it to build the whole GDK infrastructure as +universal i386/x86_64. That should be pretty easy to do, with the BasiliskIIGUI as a subport, I think. It would sure be nice to come up with some kind of GUI that doesn't require the entire GDK infrastructure to work, but what the heck -- it works.

It's trivially easy to adjust configure options for yourself and try different build options out this way. And as usual, macports takes care of all the compiler configuration and dependencies.

**Comment by rickyzhang82** [comment]
In the port file (https://github.com/macports/macports-ports/blob/master/emulators/basiliskii-devel/Portfile), I don't see they patch clock_gettime issue. I tried it as of today. It did failed in Sierra. We need PR #153:

```bash
--->  Building basiliskii-devel
Error: Failed to build basiliskii-devel: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_emulators_basiliskii-devel/basiliskii-devel/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port basiliskii-devel failed
```

log
```bash
:info:build /usr/bin/clang++ -I/opt/local/include -I../MacOSX -I./../include -I./. -I. -I./../uae_cpu -I./../slirp -DHAVE_CONFIG_H  -DOS_darwin -DDIRECT_ADDRESSING -DUNALIGNED_PROFITABLE -DX86_64_ASSEMBLY -DOPTIMIZED_FLAGS -DFPU_IEEE -D_REENTRANT -DDATADIR=\"/opt/local/share/BasiliskII\" -pipe -Os -stdlib=libc++ -arch x86_64 -I/opt/local/include/SDL -D_GNU_SOURCE=1 -D_THREAD_SAFE -fno-merge-constants -fno-gcse-sm -mdynamic-no-pic -D_REENTRANT -I/opt/local/include/gtk-2.0 -I/opt/local/lib/gtk-2.0/include -I/opt/local/include/pango-1.0 -I/opt/local/include/gio-unix-2.0/ -I/opt/local/include/cairo -I/opt/local/include/atk-1.0 -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include/libpng16 -I/opt/local/include/gdk-pixbuf-2.0 -I/opt/local/include/libpng16 -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include/freetype2 -c ./../disk.cpp -o obj/disk.o
:info:build timer_unix.cpp:48:2: error: no matching function for call to 'clock_get_time'
:info:build         clock_get_time(host_clock, &t);
:info:build         ^~~~~~~~~~~~~~
:info:build /usr/include/mach/clock.h:75:15: note: candidate function not viable: no known conversion from 'tm_time_t *' (aka 'timespec *') to 'mach_timespec_t *' (aka 'mach_timespec *') for 2nd argument
:info:build kern_return_t clock_get_time
```

**Comment by kencu** [comment]
Hi Ricky,

The one in macports is old and non-functional. The one that I made not long ago is here, and works -- MacPorts is very picky, and I haven't submitted it there as yet for them to incorporate:

<https://github.com/kencu/myports/tree/master/emulators/basiliskii>

**Comment by rickyzhang82** [comment]
I think you'd better try to send it. Otherwise, everyone just waste their man power.

**Comment by rickyzhang82** [comment]
@kencu My PR is in the upstream now. It should work fine. You can close it.

**Comment by kencu** [comment]
The MacPorts build file does a lot more "good stuff" than just fix the clock thing, so I'll keep going with it until it gets into the macports repo.

**Comment by rickyzhang82** [comment]
I see your point. If anything that needs to be patched by Macport file, we'd better move it to upstream.

**Comment by kencu** [comment]
I have entered the basiliskii port into macports, so this issue can be closed now.
