### ISSUE TITLE
BII Build failed in Mac OS Sierra

### ISSUE THREAD

**Issue by rickyzhang82** [cebix/macemu#114]
I run the following step to build BII in Sierra:
```bash
make clean
NO_CONFIGURE=1 ./autogen.sh
./configure --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --enable-threads=posix
make -j 32
```
Build failed:
```log
timer_unix.cpp:48:2: error: no matching function for call to 'clock_get_time'
        clock_get_time(host_clock, &t);
        ^~~~~~~~~~~~~~
/usr/include/mach/clock.h:75:15: note: candidate function not viable: no known conversion from 'tm_time_t *' (aka 'timespec *') to 'mach_timespec_t *' (aka 'mach_timespec *') for 2nd argument
kern_return_t clock_get_time
              ^
1 error generated.
make: *** [obj/timer_unix.o] Error 1
```

This used to work up to El Captain. I dig deeper into configure.log and found the caused of the problem is that **HAVE_CONFIG_TIME** is set as YES in Sierra. This was NO in El Captain:

config.log
```bash
configure:15286: checking for clock_gettime
configure:15286: gcc -o conftest -g -O2 -D_GNU_SOURCE=1 -D_THREAD_SAFE -I/opt/local/include/SDL   conftest.c -lm  -L/opt/local/lib -lSDLmain -Wl,-framework,AppKit -lSDL -Wl,-framework,Cocoa >&5
configure:15286: $? = 0
configure:15286: result: yes
```
Now I need to figure it out how to fix it.

**Comment by rickyzhang82** [comment]
Thanks to Apple. It fucks up clock_gettime again.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=23870

**Comment by asvitkine** [comment]
Should be fixed by
https://github.com/cebix/macemu/commit/35ca220d90b215d48211d04f91e493fb7aabe023

It was a bug in the BII code that assumed clock_gettime() was not supported
on Mac OS X.

**Comment by asvitkine** [comment]
Sorry, didn't see your https://github.com/cebix/macemu/pull/115 - accepted
that instead.
