### ISSUE TITLE
Issue with clock_sleep

### ISSUE THREAD

**Issue by Maijin** [cebix/macemu#130]
Hi guys!

I encounter the same issue as here in SheepShaver 🐑 :

https://github.com/cebix/macemu/issues/114

The patch code seems to have disappeared (the define is not in master)

```
../timer.cpp:563:3: error: no matching function for call to 'clock_sleep'
                clock_sleep(system_clock, TIME_ABSOLUTE, wakeup_time, NULL);
                ^~~~~~~~~~~
/usr/include/mach/mach.h:140:22: note: candidate function not viable: no known conversion from 'tm_time_t' (aka 'timespec') to 'mach_timespec_t' (aka 'mach_timespec') for 3rd argument
extern kern_return_t    clock_sleep(mach_port_t,
                        ^
```

**Comment by rickyzhang82** [comment]
BII or SheepShaver?

**Comment by Maijin** [comment]
SheepShaver 🐑 :)

**Comment by kevinforrestconnors** [comment]
I have the same issue.  Anyone know how to fix?  MacOS version 10.12.16

**Comment by Maijin** [comment]
@asvitkine why closing ?

**Comment by asvitkine** [comment]
Should be fixed by https://github.com/cebix/macemu/commit/e60c1aa1d753c90475053cf1e6cd969d8b7c134e
