### ISSUE TITLE
Add Travis CI to BII

### ISSUE THREAD

**Issue by rickyzhang82** [cebix/macemu#132]
Recently, I'm testing several PR in upstream repo. I think we need a automation tool to test build before I spend time to pull and test on myself.

I understood that there is unit test or integration test in BII. But it is better than have nothing.

I wrote a Travis script and a naive status update image in README in my PR branch https://github.com/rickyzhang82/macemu/tree/pr-travis-ci

@asvitkine Please let me know if you are interested in get this PR.

**Comment by dcoshea** [comment]
Perhaps this would have picked up issue #152, which is a simple compile failure in the Linux build.

**Comment by asvitkine** [comment]
I don't know very much about Travis.

How does it work? I assume CI would need to run somewhere? Where would it
run? Do we need a server? Or is this something offered by GitHub?

**Comment by barbeque** [comment]
TravisCI offers free hosting and builds to open-source projects, so hopefully no worries there.

**Comment by asvitkine** [comment]
Well, if that can work, happy to accept a PR.

**Comment by rickyzhang82** [comment]
OK. I will send this PR later. TravisCI provides Linux and Mac. But I tried that Mac has very limited resources that I never get Mac version runs. On the other hand, it is 64 bit Ubuntu available all the time. My PR will remove Mac version.

@asvitkine you need to enable TravisCI in the git repo.

**Comment by rickyzhang82** [comment]
See PR #158
