### ISSUE TITLE
SparseBundle-like disk format

### ISSUE THREAD

**Issue by MaddTheSane** [cebix/macemu#18]
I recently encountered a little thing while playing with SheepShaver: OS X's back-up utility was copying over the whole disk image I was using (2 GB). On OS X, there is a disk image format called a sparsebundle: It allows a user to have a shrinkable disk image format as a folder, with the actual content split up as 8 MB segments. I realize that having a disk image format that is limitlessly growable might cause a problem with the old Mac OS, so perhaps our format would have a set size.

**Comment by vasi** [comment]
Can we close this up?
