### ISSUE TITLE
[Feature Discussion] Port Basilisk II to iOS

### ISSUE THREAD

**Issue by rickyzhang82** [cebix/macemu#230]
I tested BII in AARCH 64 Ubuntu 20.04 under QEMU emulation. It works.

That makes me wonder if anyone has ported to iOS for recent beefy iPad or iPhone.

It should be doable but the task may be tedious. It involves 

- Converting Makefile to XCode build system
- Covert direct file I/O for config setting, static ROM file, OS image

I’m not sure what else is needed assuming iOS is POSIX compliant OS.

I wonder if anyone has made any initiative before. Thx!

**Comment by rakslice** [comment]
Take a look at https://github.com/zydeco/macemu/tree/ios/BasiliskII/src/iOS and forks of it around

**Comment by rickyzhang82** [comment]
@rakslice 

Thanks for pointing it out. The project is pretty nice. Both sound and video is working smoothly in my iPad Pro.
