### ISSUE TITLE
failure to build on Arch — unnecessary ‘AM_GNU_GETTEXT’ in ‘configure.ac’

### ISSUE THREAD

**Issue by zamfofex** [cebix/macemu#233]
It seems this is currently failing to build on Arch Linux. A friend of mine who uses Arch brought the problem up to me, and I decided to start trying to investigate through Docker.

The effect is that you’ll get an error complaining about a missing `config.rpath` file when running `./configure` (during or after `./autogen.sh`).

After investigating for a couple of hours, it seems the problem is in the `configure.ac` file. It has a line using the `AM_GNU_GETTEXT` macro, which in turn requires the `config.rpath` file to exist in the root of the project (which, from what I gathered, is a file that should be automatically generated with `gettextize`).

However, it seems that the line (introduced in f40f7ab91f70c7f31a567f47efbb5fd577b5f4e9, later modified in a46759990d33d7d1e2c7bac01459747d6180eb76), was only placed there as a means of working around an issue with GTK at the time — “`<gnome-i18n.h>` would redefine `gettext()` to nothing if `ENABLE_NLS` is not set”. Since then, the issue has been resolved, as GTK does not support disabling NLS, and [the mentioned header][glib/gi18n.h] (which has since been renamed to `glib/gi18n.h`) does not actually redefine `gettext` anymore at all.

[glib/gi18n.h]: https://gitlab.gnome.org/GNOME/glib/blob/master/glib/gi18n.h

Simply removing those lines has fixed the issue for me.

<details>
<summary>patch</summary>

~~~ diff
- dnl somehow, <gnome-i18n.h> would redefine gettext() to nothing if
- dnl ENABLE_NLS is not set, thusly conflicting with C++ <string> which
- dnl includes <libintl.h>
- AM_GNU_GETTEXT([external])
~~~

</details>

After removing those lines, I was able to build it successfully on Arch (through Docker) with the following commands:

~~~
./autogen.sh \
    --prefix=/usr \
    --enable-sdl-video \
    --enable-sdl-audio \
    --enable-jit-compiler \
    --with-bincue \
    --with-vdeplug
make
~~~

Thanks in advance for the attention!

**Comment by schinkelg** [comment]
Thank you from a fellow Arch user. This helped me getting Macemu to compile. Still can't get sound to work, but that's a different issue.
