### ISSUE TITLE
Pixel aliasing with SheepShaver on Big Sur

### ISSUE THREAD

**Issue by genericptr** [cebix/macemu#234]
Just updated to SheepShaver 2.5 and Big Sur 11.1 and I'm noticing some aliasing on the pixels. I feel like I'm getting aliasing problems on Big Sur in general (https://www.macrumors.com/how-to/disable-font-smoothing-in-macos-big-sur/) but it's noticeably bad in SheepShaver.

Zoom in on this screenshot to see what I'm talking about.

![Screen Shot 2021-01-30 at 11 09 44 AM](https://user-images.githubusercontent.com/10937186/106364446-49821d80-62ec-11eb-8fb5-b55f281d9152.png)

**Comment by RonaldPR** [comment]
SheepShaver 2.5? Are you sure you are in the right place with your question? Isn't that a SheepShaver application built from kanjitalk755/macemu source?

Maybe better ask your question in emaculation.com SheepShaver forum.

**Comment by genericptr** [comment]
I'm sorry I thought this was the official repo for SheepShaver. I even see there is a directory there in the source for SheepShaver.
