### ISSUE TITLE
Audio crackle with SDL3 enabled

### ISSUE THREAD

**Issue by parkerlreed** [cebix/macemu#278]
BasiliskII latest master with `--with-sdl3`

Audio crackles on start and stop, particularly noticeable for games with a bunch of dialog.

SDL2 build is unaffected.

Arch Linux, sdl3 1:3.1.6-3

Video showing the behavior (first is Infinite Mac showing non popping audio as that's what I had available to compare to)

https://github.com/user-attachments/assets/cfbc47dd-aefe-4697-a9b0-6901fc4a54ed

**Comment by MaddTheSane** [comment]
It could be because SDL3 dropped support for unsigned 16-bit audio.

**Comment by parkerlreed** [comment]
I just realized I posted this to the wrong macemu repo. Moving to https://github.com/kanjitalk755/macemu/issues
