### ISSUE TITLE
where is mon.h ?

### ISSUE THREAD

**Issue by ymalicy** [cebix/macemu#44]
Hi All,

i am quite new to github and to SheepShaver code...
i just want to explore the source code and see how i could track SS crashes on some OS9 applications (see my article here: http://www.emaculation.com/forum/viewtopic.php?f=20&t=8047)

so i manage to build SS on my Mac OSX 10.6 and i want to change some compiler directives to see execution traces...
for instance in file ppc-execute.cpp, you have:

#if ENABLE_MON
#include "mon.h"
#include "mon_disass.h"
#18 

however the file "mon.h" does not exist; searching in my downloaded code and this repository gives no result...

I don't use xcode yet, just compile SS using the command line as described on emaculation.

also my tracking bug method is probably not the best... i am open to learn better ways.

thanks

**Comment by asvitkine** [comment]
I've now imported the cxmon source into the project.
