### ISSUE TITLE
Get the BeOS/Haiku port working again.

### ISSUE THREAD

**Issue by pulkomandy** [cebix/macemu#66]
Hi!
Here is a set of patches to get things compiling and running on Haiku and probably also on BeOS. This is for Basilisk II only for now, Sheepshaver will need more work as the BeOS port was never updated to use the PPC emulator there.

https://bitbucket.org/haikuports/haikuports/src/51d3c8f96d6e74592dcc4ddd17ab6acad3e7aaff/app-emulation/basiliskii/patches/?at=master

I could not get multiple video modes to work, help is welcome.

**Comment by MaddTheSane** [comment]
A suggestion: fork macemu and create a pull request. GitHub makes it easy to do so.

**Comment by asvitkine** [comment]
Looks like this was merged in via: https://github.com/cebix/macemu/pull/68
