### ISSUE TITLE
[Basilisk II] Clang crash compiling fpu_ieee.cpp

### ISSUE THREAD

**Issue by m-schmitt** [cebix/macemu#69]
Using Xcode 5.1.1 or 6.1 [Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)] on OS X 10.9.5 Mavericks, clang crashes with a segmentation fault when it gets to uae_cpu/fpu/fpu_ieee.cpp.
1.  <eof> parser at end of file
2.  Code generation
3.  Running pass 'Function Pass Manager' on module './../uae_cpu/fpu/fpu_ieee.cpp'.
4.  Running pass 'X86 FP Stackifier' on function '@_Z16fpuop_arithmeticjj'
   clang: error: unable to execute command: Segmentation fault: 11
   clang: error: clang frontend command failed due to signal

Submitted bug report 20850243 to Apple.

**Comment by th-otto** [comment]
Aranym suffert from the same bug (the orginal source based on basilisk). Fix was to correct the DEFINE_ROUND_FUNC macro in mathlib.h:

#define DEFINE_ROUND_FUNC(rounding_mode_str, rounding_mode)						\
PRIVATE inline fpu_extended fp_do_round_to_ ## rounding_mode_str(fpu_extended __x)	\
{																				\
	register long double __value;						      \
	register int __ignore;						      \
	unsigned short int __cw;						      \
	unsigned short int __cwtmp;						      \
	__asm __volatile ("fnstcw %3\n\t"					      \
	"movzwl %3, %1\n\t"					      \
	"andl $0xf3ff, %1\n\t"				      \
	"orl $0x0400, %1\n\t"	/* rounding down */	      \
	"movw %w1, %2\n\t"					      \
	"fldcw %2\n\t"					      \
	"frndint\n\t"					      \
	"fldcw %3"						      \
	: "=t" (__value), "=&q" (__ignore), "=m" (__cwtmp),	      \
	"=m" (__cw)					      \
	: "0" (__x));					      \
	return __value;																\
}

(borrowed from current glibc source)

**Comment by m-schmitt** [comment]
Apple seems to think that this is the same problem that was addressed by [this patch](http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20140818/231533.html) committed to the llvm project.

Is it?

For one thing, they [explained](http://lists.cs.uiuc.edu/pipermail/llvm-commits/Week-of-Mon-20140818/231605.html) that "The patch fixes a bug where a function in X86FloatingPoint.cpp was trying to add a kill flag to a debug instruction, which was causing an assert to fire."

But my symptom is a segmentation fault. Would that be the result of a failed assertion?

I tried checking in the LLVM source at release 3.5.0, since clang is "based on LLVM 3.5svn". But I see nothing in the X86FloatingPoint.cpp source that resembles the lines surrounding the [patch](http://llvm.org/viewvc/llvm-project/llvm/trunk/lib/Target/X86/X86FloatingPoint.cpp?view=diff&r1=215961&r2=215962&pathrev=215962). 

Either the fix is in a later LLVM release or Apple is jumping to conclusions, Or both.

**Comment by th-otto** [comment]
The fix is for the assertion, but not for the segfault. When you search for 'X86 FP Stackifier' you may find similar reports that mention the assertion, but the segfault seems to be caused by another bug.. Even worse, with the fix i suggested above, i get a segfault now when using an older version of llvm (the one from Xcode 3.2.6, which is executed as llvm-gcc-4.2 and not from clang).
BTW.: both versions compile without problem with the linux version of clang...

**Comment by m-schmitt** [comment]
It should compile using Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn), i.e. clang from Yosemite.
