### ISSUE TITLE
missing files needed to build EthernetDriverFull.i

### ISSUE THREAD

**Issue by Masaq-** [cebix/macemu#72]
This archived archive contains CodeWarrior project files to build a binary blob which can be converted into EthernetDriverFull.i by hexconv.cpp:

https://web.archive.org/web/20131124123749/http://gwenole.beauchesne.free.fr/sheepshaver/files/SheepShaver-Ethernet.tar.bz2

Should these files be included in the git repository?

**Comment by asvitkine** [comment]
Thanks, I've added those files to the project.
