### ISSUE TITLE
256 color hack for SDL

### ISSUE THREAD

**Issue by rickyzhang82** [cebix/macemu#91]
I saw folks on forum asking for how to enable 8bit color depth for gaming. I added a hack to enable customized color depth in preference file. It works.

However, I don't know how to add this options in GTK UI. The overall change is minimal and not invasive. 

@cebix, do you think it is worthy to accept this pull request without UI change?

**Comment by asvitkine** [comment]
I can take a look if you send the pull request.

**Comment by rickyzhang82** [comment]
see #92

**Comment by rickyzhang82** [comment]
Any update on this pull request?  I'm also working on some fix. It may / may not has conflict with this. Please make a quick decision before I lose my momentum.
